In [1]:
import numpy as np

print(np.__version__)

1.21.5


In [2]:
a = np.array([1,2,4,56,6])
a

array([ 1,  2,  4, 56,  6])

In [3]:
b = np.array([5,6,5,4,6])
b

array([5, 6, 5, 4, 6])

In [4]:
b + a

array([ 6,  8,  9, 60, 12])

In [5]:
b*a

array([  5,  12,  20, 224,  36])

In [6]:
c = np.zeros(3)
c

array([0., 0., 0.])

In [7]:
 np.sort(a)

array([ 1,  2,  4,  6, 56])

In [8]:
c = np.array([45,56,67,88,98])
d = np.array([52,25,46,85,75])
np.concatenate((c,d))

array([45, 56, 67, 88, 98, 52, 25, 46, 85, 75])

In [9]:
np.sort(c)

array([45, 56, 67, 88, 98])

In [10]:
#np.min(d)
np.max(d)

85

In [11]:
np.mean(c)

70.8

In [12]:
np.mad(c)

AttributeError: module 'numpy' has no attribute 'mad'

In [ ]:
d.sum()

In [13]:
#d.size
v = np.expand_dims(d, axis =1)
v.


SyntaxError: invalid syntax (1746628423.py, line 3)

In [14]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1]) #Vertically stacking vectors


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [16]:
np.hstack([v1,v2,v1]) #Horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

In [17]:
array_example = np.array([[[0,1,2,3],
                           [4,5,6,7]],
                          [[0,1,2,3],
                           [4,5,6,7]],
                          [[0,1,2,3],
                          [4,5,6,7]]])
#array_example.ndim
#array_example.shape
#array_example.size


In [18]:
#A = np.arange(6)

print(A)

[0 1 2 3 4 5]


In [19]:
b = A.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [20]:
c = A.reshape(6,1)
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [21]:
np.reshape(A, newshape = (6,1), order = 'C')

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [22]:
A = np.array([[[3,4,54,32],[89,90,56,85]],[[67,67,89,54],[85,25,65,85]]])
A

array([[[ 3,  4, 54, 32],
        [89, 90, 56, 85]],

       [[67, 67, 89, 54],
        [85, 25, 65, 85]]])

In [23]:
np.sort(A)

array([[[ 3,  4, 32, 54],
        [56, 85, 89, 90]],

       [[54, 67, 67, 89],
        [25, 65, 85, 85]]])

In [24]:
print(A[1,0,:-1])

[67 67 89]


In [29]:
np.hstack(A)

array([[ 3,  4, 54, 32, 67, 67, 89, 54],
       [89, 90, 56, 85, 85, 25, 65, 85]])

In [30]:
A = np.array([1,2,3,4,5,6])
A.shape

(6,)

In [32]:
a = A[np.newaxis, :]
a.shape

(1, 6)